// src/lib/components/Quote.svelte
<script lang="ts">
	import { quotes } from "velite:content";

	const quote = quotes[(Math.random() * quotes.length) | 0];
</script>

<figure>
	<blockquote
		class="whitespace-pre-wrap fluid-text-sm"
		cite={typeof quote.source === "object" ? quote.source.url : undefined}
	>
		<p>{quote.content}</p>
	</blockquote>

	<figcaption class="mt-2 fluid-text-xs">
		<span class="text-muted-foreground">
			&mdash; {quote.quotee + (quote.source ? ", " : "")}
		</span>

		{#if quote.source}
			<cite>
				{#if typeof quote.source === "object"}
					<a class="underline" href={quote.source.url}>
						{quote.source.text}
					</a>
				{:else}
					{quote.source}
				{/if}
			</cite>
		{/if}
	</figcaption>
</figure>

// components/content/Quote.vue
<template>
	<div class="mb-10">
		<blockquote class="mb-2 whitespace-pre-wrap">"{{ quote.content }}"</blockquote>

		<p class="mt-2 text-sm text-zinc-400">
			&mdash; {{ quote.quotee + (quote.source ? ", " : "") }}

			<cite v-if="quote.source">
				<NuxtLink v-if="typeof quote.source === 'object'" :href="quote.source.url">
					{{ quote.source.text }}
				</NuxtLink>

				<template v-else>{{ quote.source }}</template>
			</cite>
		</p>
	</div>
</template>

<script setup lang="ts">
import quotes from "../../content/quotes.json";

const quote = quotes[(Math.random() * quotes.length) | 0];
</script>
